description = 'Sample Table Device'

group = 'optional'

pvprefix = '192.168.21.11:epics_lib:'

devices = dict(
	phi = device('nicos_batan.dn1.devices.epics.EpicsMotorBatan',
	      description = 'Phi Axis Motor',
	      writepv = pvprefix + 'Phi_Pos',
	      readpv = pvprefix + 'Phi_Pos',
	      abslimits = (0, 360),
	      unit = 'deg',
	      speed = 5,
	),
	kai = device('nicos_batan.dn1.devices.epics.EpicsMotorBatan',
	      description = 'kai Axis Motor',
	      writepv = pvprefix + 'Kai_Pos',
	      readpv = pvprefix + 'Kai_Pos',
	      abslimits = (0, 360),
	      unit = 'deg',
	      speed = 5,
	),
	omega = device('nicos.devices.generic.VirtualMotor',
	      description = 'Omega Axis Motor',
	      abslimits = (0, 360),
	      unit = 'deg',
	      speed = 5,
	),
	xs = device('nicos.devices.generic.VirtualMotor',
	      description = 'X Axis Motor',
	      abslimits = (-70, 70),
	      unit = 'mm',
	      speed = 5,
	),
	ys = device('nicos.devices.generic.VirtualMotor',
	      description = 'Y Axis Motor',
	      abslimits = (-70, 70),
	      unit = 'mm',
	      speed = 3,
	),
	zs = device('nicos.devices.generic.VirtualMotor',
	      description = 'Z Axis Motor',
	      abslimits = (0, 60),
	      unit = 'mm',
	      speed = 1,
	),
	s2 = device('nicos.devices.epics.EpicsReadable',
	      description = 'S2 Encoder Value',
	      readpv = pvprefix + 'S2-enc',
	      unit = 'deg',
	),
)
